### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./checkpoints/nextgpt-v1.5-7b.

### ISSUE THREAD

**Issue by ozgurcelik** [NExT-GPT/NExT-GPT#106]
I am getting

Traceback (most recent call last):
  File "predict.py", line 219, in <module>
    predictor.setup(model_base=None, model_name="nextgpt-v1.5-7b", model_path="./checkpoints/nextgpt-v1.5-7b", load_8bit=False, load_4bit=False)
  File "predict.py", line 114, in setup
    self.tokenizer, self.model, self.image_processor, self.video_processor, self.audio_processor, self.context_len, self.model_config = load_pretrained_model(model_path, model_base, model_name, load_8bit=load_8bit, load_4bit=load_4bit) 
  File "/Users/dirtem/Desktop/2024-1/xvila/NExT-GPT/nextgpt/model/builder.py", line 104, in load_pretrained_model
    model = NextGPTLlamaForCausalLM.from_pretrained(
  File "/Users/dirtem/miniconda3/envs/nextgpt/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3558, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory ./checkpoints/nextgpt-v1.5-7b.

error. I dowloaded https://huggingface.co/ChocoWu/nextgpt_7b_tiva_v0 model and put the files there directly under the ./checkpoints/nextgpt-v1.5-7b . The code that returns error is 

model = NextGPTLlamaForCausalLM.from_pretrained(
                model_path,
                low_cpu_mem_usage=True,
                **kwargs
            )
            
model path is /Users/dirtem/Desktop/2024-1/xvila/NExT-GPT/checkpoints/nextgpt-v1.5-7b

Has anyone had similar problems? How did you solve it?

**Comment by anonymous-atom** [comment]
The latest model weights are still be to release by the authors, you can use the legacy code with current weights on huggingface

**Comment by Amber0913** [comment]
same question! where can I find "pytorch_model.bin, model.safetensors, tf_model.h5, model.ckpt.index".
