### ISSUE TITLE
AssertionError: (tensor([32002, 32001, 16198, 32019], device='cuda:0'), [32002, 32003, 32004, 32005])

### ISSUE THREAD

**Issue by GOD1998LIU** [NExT-GPT/NExT-GPT#66]
This is the issue that i meet, i want NExT-GPT give me an image about sky, but it failed.

text prompt:  ### Human:  give me an image about sky.
### Assistant:
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
all_gen_img_idx:  [115]
all_gen_vid_idx:  [94]
all_gen_aud_idx:  [149]
`text_config_dict` is provided which will be used to initialize `CLIPTextConfig`. The value `text_config["id2label"]` will be overriden.
Traceback (most recent call last):
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/data/lb/lb/miniconda3/envs/nextgpt/lib/python3.8/site-packages/gradio/utils.py", line 641, in wrapper
    response = f(*args, **kwargs)
  File "demo_app.py", line 308, in predict
    response = model.generate({
  File "/data0/lb/lb/NExT-GPT/code/model/anyToImageVideoAudio.py", line 978, in generate
    img_outputs = self.generate_images(generated_ids, generated_image_embeddings, all_gen_img_idx, None,
  File "/data0/lb/lb/NExT-GPT/code/model/anyToImageVideoAudio.py", line 768, in generate_images
    assert generated_ids[0,
AssertionError: (tensor([32002, 32001, 16198, 32019], device='cuda:0'), [32002, 32003, 32004, 32005])

**Comment by manushree635** [comment]
can you elaborate on how you fixed this
