### ISSUE TITLE
4.2. Deploying Gradio Demo -- code bug -- No module named 'data'

### ISSUE THREAD

**Issue by yunjing77** [NExT-GPT/NExT-GPT#86]
我首先按照#4.1去下载模型，放在指定的目录下：
imagebind_huge.pth放在[[./ckpt/pretrained_ckpt/imagebind_ckpt/huge]]
vicuna-7b-delta-v0放在 [[./ckpt/pretrained_ckpt/vicuna_ckpt/]]
nextgpt_7b_tiva_v0 放在[[./ckpt/delta_ckpt/nextgpt/7b_tiva_v0]]
然后按照#4.2执行scripts/app.sh脚本的时候报错了
=======================================
4.2. Deploying Gradio Demo
Upon completion of the checkpoint loading, you can run the demo locally via:
```
cd ./code
bash scripts/app.sh
```
=======================================

报错信息如下：
(nextgpt) [root@311 multimodel]# cd NExT-GPT/
(nextgpt) [root@311 NExT-GPT]# ls
ckpt  code  data  figures  LICENSE.md  README.md  requirements.txt
(nextgpt) [root@311 NExT-GPT]# cd code
(nextgpt) [root@311 code]# bash scripts/app.sh 
Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "demo_app.py", line 8, in <module>
    from model.anyToImageVideoAudio import NextGPTModel
  File "/data/ivb/multimodel/NExT-GPT/code/model/__init__.py", line 4, in <module>
    from .agent import DeepSpeedAgent
  File "/data/ivb/multimodel/NExT-GPT/code/model/agent.py", line 4, in <module>
    from header import *
  File "/data/ivb/multimodel/NExT-GPT/code/header.py", line 29, in <module>
    import data
ModuleNotFoundError: No module named 'data'

**Comment by Aloukik21** [comment]
having same issue..
did you find any solution?

**Comment by kqcode** [comment]
@yj77-enen I think you can solve this problem by replacing 'mode' with 'model'.

**Comment by WYY220062** [comment]
Hi @yj77-enen, if it is possible can I have your vicuna-7b-delta-v0 parameters files, I never heared about from meta, can not get the originial LLaMA weights. Thank you in advance.
